DROP DATABASE IF EXISTS CompanyDB;
CREATE DATABASE CompanyDB;
USE CompanyDB;

CREATE TABLE Employees (
	`EmployeeID` INT PRIMARY KEY AUTO_INCREMENT,
    `FirstName` VARCHAR(50) NOT NULL,
    `LastName` VARCHAR(50) NOT NULL,
    `HireDate` DATE NOT NULL,
    `Salary` INT
);

ALTER TABLE Employees
ADD COLUMN Department INT NOT NULL;

 ALTER TABLE Employees
 MODIFY COLUMN Salary DECIMAL(10, 2);
